### ISSUE TITLE
Support graphical veiled mods in item hover

### ISSUE THREAD

**Issue by thailyn** [Stickymaddness/Procurement#923]
Right now veiled mods on items simply show up as `Veiled Prefix` or `Veiled Suffix`.  In game and on the official website, the veiled mods show up as an animated graphic.  On the website, this is performed with a CSS animation.  There are six variations each for veiled prefixes and suffixes, and specific veiled mods belong to one variant (in the JSON, they show up as `Prefix01` or `Suffix06`, for example), and each variant has its own, very wide, PNG file.  The animation is performed by shifting a fixed-width window on this background image.

There is a fixed width to the window, and a fixed number of steps, so my theory is that each step essentially shifts the visible part of the background image to the next "frame" of the animation.  For all affixes, the final `background-position` is 0px.  For prefixes, the initial `background-position` is -14220px, and the window has a width of 158px, and the window does divide into the image 90 times.  For suffixes, the initial `background-position` is -7650px, but the window size is only 85px, so the window size again evenly divides into the background image's width 90 times.

I'm pretty sure we could do something similar in WPF, but at the moment it's beyond my current understanding.  With a little research I could implement something, or someone more proficient could do it first.

Excerpt from the website's CSS:
``` CSS
@-webkit-keyframes animate-veiled-mod {
  100% {
    background-position: 0; } }

@-moz-keyframes animate-veiled-mod {
  100% {
    background-position: 0; } }

@-ms-keyframes animate-veiled-mod {
  100% {
    background-position: 0; } }

@-o-keyframes animate-veiled-mod {
  100% {
    background-position: 0; } }

@keyframes animate-veiled-mod {
  100% {
    background-position: 0; } }

.itemPopupContainer {
  position: relative;
  text-align: center;
  z-index: 10000;
  min-width: 262.88032px;
  max-width: 742.39351px;
  -webkit-pointer-events: none;
  -moz-pointer-events: none;
  pointer-events: none; }
  .itemPopupContainer .veiledMod .lc.prefix, .itemPopupContainer .veiledMod .lc.suffix {
    padding: 0;
    -webkit-animation: animate-veiled-mod 3s steps(90) reverse infinite;
    -moz-animation: animate-veiled-mod 3s steps(90) reverse infinite;
    -ms-animation: animate-veiled-mod 3s steps(90) reverse infinite;
    -o-animation: animate-veiled-mod 3s steps(90) reverse infinite;
    animation: animate-veiled-mod 3s steps(90) reverse infinite;
    will-change: background-position;
    white-space: nowrap; }
  .itemPopupContainer .veiledMod .lc.prefix {
    width: 158px;
    background-position: -14220px;
    -webkit-user-select: auto;
    -moz-user-select: auto;
    user-select: auto;
    color: transparent; }
  .itemPopupContainer .veiledMod .lc.prefix01 {
    background-image: url('/image/item/veiled/prefix_01.png?1544695939000'); }
  .itemPopupContainer .veiledMod .lc.prefix02 {
    background-image: url('/image/item/veiled/prefix_02.png?1544695939000'); }
  .itemPopupContainer .veiledMod .lc.prefix03 {
    background-image: url('/image/item/veiled/prefix_03.png?1544695940000'); }
  .itemPopupContainer .veiledMod .lc.prefix04 {
    background-image: url('/image/item/veiled/prefix_04.png?1544695940000'); }
  .itemPopupContainer .veiledMod .lc.prefix05 {
    background-image: url('/image/item/veiled/prefix_05.png?1544695940000'); }
  .itemPopupContainer .veiledMod .lc.prefix06 {
    background-image: url('/image/item/veiled/prefix_06.png?1544695940000'); }
  .itemPopupContainer .veiledMod .lc.suffix {
    width: 85px;
    background-position: -7650px;
    -webkit-user-select: auto;
    -moz-user-select: auto;
    user-select: auto;
    color: transparent; }
  .itemPopupContainer .veiledMod .lc.suffix01 {
    background-image: url('/image/item/veiled/suffix_01.png?1544695940000'); }
  .itemPopupContainer .veiledMod .lc.suffix02 {
    background-image: url('/image/item/veiled/suffix_02.png?1544695940000'); }
  .itemPopupContainer .veiledMod .lc.suffix03 {
    background-image: url('/image/item/veiled/suffix_03.png?1544695940000'); }
  .itemPopupContainer .veiledMod .lc.suffix04 {
    background-image: url('/image/item/veiled/suffix_04.png?1544695940000'); }
  .itemPopupContainer .veiledMod .lc.suffix05 {
    background-image: url('/image/item/veiled/suffix_05.png?1544695940000'); }
  .itemPopupContainer .veiledMod .lc.suffix06 {
    background-image: url('/image/item/veiled/suffix_06.png?1544695940000'); }
```
